[app]
    name = simple_monitoring
    metrics = simple_monitoring.*
    private charts = no
    gaps when not collected = no
    history = 3600

[dictionary]
    load_test_score = Load test score

[load_test]
    name = load_test
    title = Local load test signal
    family = lab
    context = simple_monitoring.load_test
    units = score
    priority = 91000
    type = line
    dimension = simple_monitoring.load_test_score score last 1 1
